=== VijayEluri/indivo_client_java/client_codegen/src/main/xml/api_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.indivo.org/api_schema"
  xmlns:tns="http://www.indivo.org/api_schema"
  >

	<xs:element name="api">
    <xs:complexType>
    	<xs:sequence>
    		<xs:element name="method" type="tns:Method" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:complexType name="Method">
    	<xs:sequence>
    		<xs:element name="call" type="tns:callType"></xs:element>
    		<xs:element name="oauth_legged" type="tns:oauth_leggedType"></xs:element>
    		<xs:element name="response" type="tns:responseType"></xs:element>
    		<xs:element name="put_post_data" type="tns:put_post_dataType" minOccurs="0"></xs:element>
    		<xs:element name="query_opts" type="tns:query_optsType" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>


    <xs:complexType name="callType">
    	<xs:attribute name="method" type="xs:string"></xs:attribute>
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    	<xs:attribute name="url" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="responseType">
    	<xs:sequence maxOccurs="unbounded" minOccurs="0">
    		<xs:element name="response" type="tns:responseType"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="response_format" type="xs:string"></xs:attribute>
    	<xs:attribute name="element" type="xs:string"></xs:attribute>
    	<xs:attribute name="attribute" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="oauth_leggedType">
    	<xs:attribute name="two_legged" type="xs:string"></xs:attribute>
    	<xs:attribute name="three_legged" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="put_post_dataType">
    	<xs:sequence maxOccurs="unbounded" minOccurs="0">
    		<xs:element name="key">
    			<xs:complexType>
    				<xs:attribute name="name" type="xs:string"></xs:attribute>
    			</xs:complexType></xs:element>
    	</xs:sequence>
    	<xs:attribute name="format" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="query_optsType">
    	<xs:sequence maxOccurs="unbounded" minOccurs="1">
    		<xs:element name="qopt">
    			<xs:complexType>
    				<xs:attribute name="name" type="xs:string"></xs:attribute>
    			</xs:complexType>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

</xs:schema>

=== VijayEluri/indivo_client_java/client_codegen/src/main/py/detailed_api.xml
<?xml version="1.0" ?><api xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="api_schema.xsd">
<!--A principal has full control over a record if it is the owner of the record, 
    or if it has a full share of the record.
Apps never fully share a record, only accounts do.
-->
  <method>
    <call method="post" name="post_access_token" url="/oauth/access_token"/>
    <oauth_legged two_legged="two_legged"/>
    <response response_format="URL_ENCODED"/>
  </method>
  <method>
    <call method="post" name="post_document" url="/records/{RECORD_ID}/documents/"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response attribute="id" element="Document" response_format="XML"/>
    <put_post_data/>
  </method>
  <method>
    <call method="put" name="post_document_ext" url="/records/{RECORD_ID}/documents/external/{APP_ID}/{EXTERNAL_ID}"/>
    <oauth_legged three_legged="three_legged"/>
    <response attribute="id" element="Document" response_format="XML"/>
    <put_post_data/>
  </method>
  <method>
    <call method="get" name="account_inbox" url="/accounts/{ACCOUNT_ID}/inbox/"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="XML"/>
    <query_opts><qopt name="status"/><qopt name="order_by"/><qopt name="limit"/><qopt name="include_archive"/><qopt name="offset"/></query_opts>
  </method>
  <method>
    <call method="get" name="account_inbox_message" url="/accounts/{ACCOUNT_ID}/inbox/{MESSAGE_ID}"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="XML"/>
  </method>
  <method>
    <call method="post" name="account_message_archive" url="/accounts/{ACCOUNT_ID}/inbox/{MESSAGE_ID}/archive"/>
    <oauth_legged three_legged="three_legged"/>
    <response element="ok" response_format="XML"/>
  </method>
  <method>
    <call method="post" name="account_inbox_message_attachment_accept" url="/accounts/{ACCOUNT_ID}/inbox/{MESSAGE_ID}/attachments/{ATTACHMENT_NUM}/accept"/>
    <oauth_legged three_legged="three_legged"/>
    <response element="ok" response_format="XML"/>
  </method>
  <method>
    <call method="get" name="account_notifications" url="/accounts/{ACCOUNT_ID}/notifications/"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="XML"/>
    <query_opts><qopt name="status"/><qopt name="limit"/><qopt name="order_by"/><qopt name="offset"/></query_opts>
  </method>
  <method>
    <call method="post" name="message_account" url="/accounts/{ACCOUNT_ID}/inbox/"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="body"/><key name="severity"/><key name="message_id"/><key name="subject"/></put_post_data>
  </method>
  <method>
    <call method="get" name="get_recapp_documents" url="/records/{RECORD_ID}/apps/{APP_ID}/documents/"/>
    <oauth_legged three_legged="three_legged"/>
    <response attribute="record_id" element="Documents" response_format="XML">
      <response attribute="id" element="Document"/>
    </response>
    <query_opts><qopt name="status"/><qopt name="order_by"/><qopt name="type"/><qopt name="limit"/><qopt name="offset"/></query_opts>
  </method>
  <method>
    <call method="post" name="create_session" url="/oauth/internal/session_create"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="URL_ENCODED"/>
    <put_post_data format="url_encoded"><key name="username"/><key name="password"/><key name="system"/></put_post_data>
  </method>
  <method>
    <call method="get" name="account_search" url="/accounts/search?{PARAMETERS}"/>
    <oauth_legged two_legged="two_legged"/>
    <response response_format="XML"/>
    <query_opts><qopt name="fullname"/><qopt name="contact_email"/></query_opts>
  </method>
  <method>
    <call method="post" name="account_forgot_password" url="/accounts/{ACCOUNT_ID}/forgot-password"/>
    <oauth_legged two_legged="two_legged"/>
    <response response_format="XML"/>
  </method>
  <method>
    <call method="get" name="account_info" url="/accounts/{ACCOUNT_ID}"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response response_format="XML"/>
  </method>
  <method>
    <call method="get" name="account_primary_secret" url="/accounts/{ACCOUNT_ID}/primary-secret"/>
    <oauth_legged two_legged="two_legged"/>
    <response response_format="XML"/>
  </method>
  <method>
    <call method="post" name="add_auth_system" url="/accounts/{ACCOUNT_ID}/authsystems/"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="username"/><key name="password"/><key name="system"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_set_password" url="/accounts/{ACCOUNT_ID}/authsystems/password/set"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="password"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_change_password" url="/accounts/{ACCOUNT_ID}/authsystems/password/change"/>
    <oauth_legged three_legged="three_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="new"/><key name="old"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_initialize" url="/accounts/{ACCOUNT_ID}/initialize/{PRIMARY_SECRET}"/>
    <oauth_legged three_legged="three_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="secondary_secret"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_reset" url="/accounts/{ACCOUNT_ID}/reset"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
  </method>
  <method>
    <call method="post" name="account_username_set" url="/accounts/{ACCOUNT_ID}/authsystems/password/set-username"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="username"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_info_set" url="/accounts/{ACCOUNT_ID}/info-set"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="contact_email"/><key name="full_name"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_set_state" url="/accounts/{ACCOUNT_ID}/set-state"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <put_post_data format="url_encoded"><key name="state"/></put_post_data>
  </method>
  <method>
    <call method="post" name="account_secret_resend" url="/accounts/{ACCOUNT_ID}/secret-resend"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
  </method>
  <method>
    <call method="get" name="check_account_secrets" url="/accounts/{ACCOUNT_ID}/check-secrets/{PRIMARY_SECRET}?{PARAMETERS}"/>
    <oauth_legged two_legged="two_legged"/>
    <response element="ok" response_format="XML"/>
    <query_opts><qopt name="secondary_secret"/></query_opts>
  </method>
  <method>
    <call method="get" name="read_record" url="/records/{RECORD_ID}"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response attribute="id" element="Record" response_format="XML"/>
  </method>
  <method>
    <call method="post" name="replace_document" url="/records/{RECORD_ID}/documents/{DOCUMENT_ID}/replace"/>
    <oauth_legged three_legged="three_legged" two_legged="two_legged"/>
    <response attribute="id" element="Document" response_format="XML"/>
    <put_post_data/>
  </method>
  <method>
    <call method="get" name="read_document_versions" url="/records/{RECORD_ID}/documents/{DOCUMENT_ID}/versions/?{PARAMETERS}"/>
    <oauth_legged three_legged="three_legged"/>
    <response attribute="record_id" element="Documents" response_format="XML">
      <response attribute="id" element="Document"/>
    </response>
    <query_opts><qopt name="status"/><qopt name="limit"/><qopt name="order_by"/><qopt name="offset"/></query_opts>
  </method>
  <method>
    <call method="put" name="put_document_relate_existing" url="/records/{RECORD_ID}/documents/{DOCUMENT_ID}/rels/{REL_TYPE}/{OTHER_DOCUMENT_ID}"/>
    <oauth_legged three_legged="three_legged"/>
    <response attribute="record_id" element="Documents" response_format="XML">
      <response attribute="id" element="Document"/>
    </response>
  </method>
  <method>
    <call method="post" name="post_request_token" url="/oauth/request_token"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="URL_ENCODED"/>
    <put_post_data format="url_encoded"><key name="indivo_record_id"/><key name="indivo_carenet_id"/></put_post_data>
  </method>
  <method>
    <call method="post" name="claim_request_token" url="/oauth/internal/request_tokens/{REQUEST_TOKEN}/claim"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="PLAIN_TEXT"/>
  </method>
  <method>
    <call method="get" name="get_request_token_info" url="/oauth/internal/request_tokens/{REQUEST_TOKEN}/info"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="XML"/>
  </method>
  <method>
    <call method="post" name="approve_request_token" url="/oauth/internal/request_tokens/{REQUEST_TOKEN}/approve"/>
    <oauth_legged three_legged="three_legged"/>
    <response response_format="URL_ENCODED"/>
    <put_post_data format="url_encoded"><key name="record_id"/><key name="carenet_id"/></put_post_data>
  </method>
  <method>
    <call method="get" name="verify_surl" url="/oauth/internal/surl-verify"/>
